### PR TITLE
Changes in Exchange for fishing Activity

### PR DESCRIPTION
**Pull request by AdityaPadhy**

### CODE REVIEW

**Comment by thomasfanto** [comment]
Here is a lot of changes and enhancements. I don't see any tests written for it.
How can we proof that it works ?

**Review by thomasfanto — DISMISSED** [review]
Here is a lot of changes and enhancements. I don't see any tests written for it.
Tests must be written to ensure that the code still works as it evolves

**Review by ebrygg — APPROVED** [review]
ok

**Comment by ebrygg** [comment]
please test me

**Comment by ebrygg** [comment]
test me

**Pull request merged**
