### PR TITLE
Bel dev

### PR DESCRIPTION
**Pull request by stainii**
Make it possible to receive and send FLUX messages for the Sales module.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Hi,

Thanks for the pull request, and sorry for the delay.

Please remove any log statements like below
--
  long before = System.currentTimeMillis();
 +                jc = JAXBContext.newInstance(clazz);
 +                contexts.put(clazz.getName(), jc);
 +                LOG.debug("Stored contexts: {}", contexts.size());
 +                LOG.debug("JAXBContext creation time: {}", (System.currentTimeMillis() - before));
--

Recommend using http://databene.org/contiperf.html, to validate perf requirements using junit

The ExchangeModuleRequestMapperTest  looks good, please add test for all the new methods in the other Mappers as well.

Best regards

**Comment by stainii** [comment]
Thanks for the tip, @jamessorling! Got rid of the log lines.

**Review by petermcj — CHANGES_REQUESTED** [review]
Instead of introducing guava (adds 2MB extra) just for nullcheck use standard bean validation @NotNull or java standard java.utils.Objects.requireNonNull

**Review by thomasfanto — DISMISSED** [review]
Here is a lot of changes and enhancements. I don't see any tests written for it.
Tests must be written to ensure that the code still works as it evolves

**Review by ebrygg — APPROVED** [review]
Ok, guava is a bit unnecessary, might remove this later.

**Pull request merged**
